global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'caddy'
    static_configs:
      - targets: ['caddy:2019']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'alloy'
    static_configs:
      - targets: ['alloy:12345']
      
  - job_name: 'actual_server'
    static_configs:
      - targets: ['actual_server:5006']

  # Add additional targets here as needed
  # Example:
  # - job_name: 'node-exporter'
  #   static_configs:
  #     - targets: ['node-exporter:9100']